export {
  PixelEngine,
  SETTLE_STABLE_THRESHOLD,
  SETTLE_TIMEOUT_FRAMES,
  SETTLE_SWAP_THRESHOLD,
  DEFAULT_AMBIENT_TEMPERATURE,
  DEFAULT_GROWTH_INTERVAL,
  DEFAULT_LIQUID_DISPERSION,
  DEFAULT_PRESSURE_VISIT_LIMIT,
  DEFAULT_FRACTURE_PER_FRAME,
  VELOCITY_CELL_UNIT,
  DEFAULT_VELOCITY_DRAG,
  VELOCITY_REMAINDER_HEADROOM,
  VELOCITY_MAX_STEPS,
  VELOCITY_GRAVITY_SCALE,
  OUTLET_VELOCITY_EFFICIENCY,
  OUTLET_LATERAL_SPREAD,
  MIN_OUTLET_SURPLUS,
  EXPLOSION_VELOCITY_SCALE,
  HEAT_EPSILON,
  CONDUCTION_MAX,
  INSULATED_EXPOSURE,
  packGrowth,
  unpackGrowth,
  type PixelEngineOptions,
  type ExplosionHook,
  type LiquidInjection,
  type InjectionResult,
  type InjectionRejectionReason,
  type PressureSourceOptions,
  type PressureSourceState,
  type PressureSourceFractureOptions,
} from './engine.js';
export { neighborFrame, fillNeighborFrame, octantOffset } from './neighbors.js';
export type { NeighborFrame, CellOffset } from './types.js';
