export {
  MaterialType,
  Materials,
  materialDefs,
  isThermal,
  isImmobile,
  needsSupport,
  hasGrowth,
  hasPressure,
  hasPressureStrength,
  hasFragmentation,
  hasYieldCurve,
  yieldThicknessAt,
  TERRAIN_SOLIDS,
  isTerrainSolid,
  type MaterialDef,
  type Octant,
  type GrowthRule,
  type SpreadRule,
  type TipRule,
  type AggregateRule,
} from './materials.js';
